version: '3'

services:
  image-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
    - ./src/:/image-api
    command:
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
